spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 529140518090422
            client-secret: e6ef067c1fa6db45adaf891cb1ae9889
            scope:
              - email
              - profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

  datasource:
    url: jdbc:mysql://localhost:3306/pmhdv?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  jackson:
    serialization:


      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


server:
  ssl:
    key-store: src/main/resources/springboot.keystore
    key-store-password: 123456
    keyAlias: tomcat
    protocol: TLS
  port: 8081


